---
- name: Install pycurl
  apt: pkg=python-pycurl update_cache=yes cache_valid_time=600
- name: Install python-dev
  apt: pkg=python-dev
- name: Remove platform python crypto
  apt: pkg=python-crypto state=absent
- name: Install pip
  apt: pkg=python-pip update_cache=yes
- name: Install docker-py
  pip: name="docker-py"
- name: Install pycrypto
  pip: name="pycrypto"
